name = "your-worker-name"
main = "src/index.ts"
compatibility_date = "2022-04-05"

[dev]
port = 5555

[[durable_objects.bindings]]
name = "SIGNALING_ROOM"
class_name = "SignalingRoom"

[[migrations]]
tag = "v1"
new_classes = ["SignalingRoom"]